### ISSUE TITLE
Occurred Type Error, When use Vue.component

### ISSUE THREAD

**Issue by kazupon** [ngsru/vue-server#4]
When we execute the `examples/items/index.js`, Occurred error the below.

```
Vue.component('item', {
    ^

TypeError: Vue.component is not a function
    at Object.<anonymous> (/Users/kazupon/Projects/my/vue-server/examples/items/index.js:6:5)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
```

**Comment by fullfs** [comment]
@kazupon thanks for the report!
Looks like I've broke it in last release. Try ```0.4.0-beta.5```, should be ok there.
Will fix the issue soon

**Comment by fullfs** [comment]
@kazupon should work now :)
https://github.com/ngsru/vue-server/releases/tag/0.4.0-beta.7
